//EX1 ON PRINTING METHODS
public class EX1										//MAIN CLASS
{
	public static void main(String arg[])
	{
		System.out.print("RAMANA"+"PALADUGU"); 			//AFTER PRINTING THE MESSAGE CURSOR IS IN THE SAME LINE
		System.out.println("USHA"+2);					//AFTER PRINTING THE MESSAGE CURSOR IN THE NEXT LINE
		System.out.printf("PRASANTH %s","PALADUGU"); 	//AFTER PRINTING THE MESSAGE CURSOR IN THE SAME LINE AND IT IS C METHOD OF PRINTING
		System.out.format("BHAVYA %s","P"); 			//AFTER PRINTING THE MESSAGE CURSOR IN NEXT LINE AND USED TO SEND OUT PUT TO ANOTHER PROGRAM
	}
}