//EX20 ON USER DEFINED METHODS USING V-ARGUMENT
public class EX20
{
	//static int sum(int x,int y)					//ACTUALL TYPE OF DECLARING VARIBLES IN STATIC
	static int sum(int...x)							//VARGUMENT IT GIVES OUTPUT WITH NUMBER OF VARIBLES==>0 TO 4CRORES VARIBLES
	{												//VARGUMENTS INTERNALLY USES UNI-DIRECTIONAL ARRAY
		int p=0;
		for(int t:x)								//FOR EACH LOOP IS USED FOR EXTRACTING DATA IN THE 'x'
		{
			p=p+t;
		}
		return p;
	}
	public static void main(String [] arg)
	{
		System.out.println("SUM IS "+sum(11,22));		//NUMBER OF ACTUALL VARIBLES MATCHES NUMBER OF FORMAL/TEMPERORY VARIABLES PROGRAM EXECUTED
		System.out.println("SUM IS "+sum(11,22,33));	//THIS ERROR OCCURS==>ACTUAL AND FORMAL ARGUMENT LISTS DIFFER IN LENGTH BECAUSE FORMAL VARIABLES 2 AND ACTUAL VARIABLES 3 MIS MATCH
	}
}